# -*- coding: utf-8 -*-
"""Score.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kUAetIMZcUOnoqKV-G6Y9pL5Z1OuXZYJ
"""

score = input().split()
count = 0
total = 0

for i in score:
    if int(i) < 60:
        count += 1
    total += int(i)

average = total / len(score)

print(count)
print(f"{average:.2f}")